export const CurlmateSkill = {
  id: "curlmate",
  name: "Curlmate",
  description: "A skill that that tells you about Curlmate and how to use it.",
  skillEndpoint: "https://api.curlmate.dev/skill",
  skillEndpointMethod: "GET",
  skillEndpointAuthMethod: "None",
  authUrlEndpoint: "https://api.curlmate.dev/auth-url",
  authUrlEndpointMethod: "GET",
  authUrlEndpointAuthMethod: "Bearer JWT",
  authUrlEndpointHeaders: {
    "Content-Type": "application/json",
    "x-connection":
      "response from /connections endpoint formatted as connectionHash:service",
  },
  connectionsEndpoint: "https://api.curlmate.dev/connections",
  connectionsEndpointMethod: "GET",
  connectionsEndpointAuthMethod: "Bearer JWT",
  jwtEndpoint: "https://api.curlmate.dev/jwt",
  jwtEndpointAuthMethod: "Bearer API Key",
  jwtEndpointMethod: "GET",
  claudeConfigEndpoint: "https://api.curlmate.dev/claude-config",
  claudeConfigEndpointAuthMethod: "Bearer JWT",
  claudeConfigEndpointMethod: "GET",
  opencodeConfigEndpoint: "https://api.curlmate.dev/opencode-config",
  opencodeConfigEndpointAuthMethod: "Bearer JWT",
  opencodeConfigEndpointMethod: "GET",
  tokenEndpoint: "https://api.curlmate.dev/token",
  tokenEndpointAuthMethod: "Bearer JWT",
  tokenEndpointMethod: "POST",
  tokenEndpointHeaders: {
    "Content-Type": "application/json",
    "x-connnection":
      "response from /connections, /claude-config or /opencode-config endpoints formatted as connectionHash:service",
  },
};
